# KARL ISAIAH BUENAFE

Write a Python function that takes two three-dimensional numeric data sets and adds them componentwise.

In [1]:
import numpy as np

In [41]:
def DsetAddition(D1,D2):
    df1=np.array(D1)
    df2=np.array(D2)
    Dsum= df1+df2 
    
    return Dsum

print('Data Set Addition')

D1= eval(input('Please give a 3D Data Set (Use this format:[[[a1,a2,...,ax],[b1,b2,...,bx]],[[c1,c2,...,cx],[d1,d2,...,dx]]])\n'))
D2=eval(input('\n\nPlease give a 3D Data Set (Use this format:[[[a1,a2,...,ax],[b1,b2,...,bx]],[[c1,c2,...,cx],[d1,d2,...,dx]]])\n'))

DSsum=DsetAddition(D1,D2)

print(f'\nThe sum of the two 3D Data Sets is: \n{DSsum}')

Data Set Addition
Please give a 3D Data Set (Use this format:[[[a1,a2,...,ax],[b1,b2,...,bx]],[[c1,c2,...,cx],[d1,d2,...,dx]]])
[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]


Please give a 3D Data Set (Use this format:[[[a1,a2,...,ax],[b1,b2,...,bx]],[[c1,c2,...,cx],[d1,d2,...,dx]]])
[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]

The sum of the two 3D Data Sets is: 
[[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]]


Give a complete ArrayDeque implementation of the double-ended queue ADT

In [38]:
class ArrayDeque:
    
    DEFAULT_CAPACITY = 10 
    
    def __init__(self):
        self._data = [None] * ArrayDeque.DEFAULT_CAPACITY 
        self._size = 0
        self._front = 0
        
    def __len__(self):
        return self._size
    
    
    def is_empty(self):
        return self._size == 0
    
    
    def first(self):
        if self.is_empty():
            raise Empty("Queue is empty") 
        return self._data[self._front]
    
    def last(self):
        if self.is_empty():
            raise Empty("Queue is empty") 
        back=(self._front + self._size-1)% len(self._data)
            
        return self._data[back]
    
    def enqueue_front(self, e):
        
        if self._size==len(self._data):
            self._resize(2*len(self._data)) 
        
        self._front=(self._front-1) % len(self._data)
        self._data[self._front]=e
        self._size += 1
        
    def enqueue_back(self, e):
        
        if self._size==len(self._data):
            self._resize(2*len(self._data)) 
        
        avail=(self._front+self._size) % len(self._data)
        self._data[avail]=e
        self._size +=1

    def dequeue_front(self):
        
        if self.is_empty():
            raise Empty("Queue is empty") 
        
        answer=self._data[self._front]
        self._data[self._front]= None
        self._front= (self._front + 1) % len(self._data)
        self._size-=1
        
        return answer
    
    def dequeue_back(self):
        
        if self.is_empty():
            raise Empty("Queue is empty") 
        
        back=(self._front + self._size-1)% len(self._data)
        answer=self._data[back]
        self._data[back]= None
        self._size-=1
        
        return answer
    
    def resize(self,cap):
        old=self._data
        self._data=[None] * cap
        walk=self._front
        for k in range(self._size):
            self._data[k]=old[walk]
            walk=(1+walk)%len(old)
        self._front=0
        
    def __str__(self):
        items = [self._data[(self._front + i) % len(self._data)] for i in range(self._size)]
        return f'Deque: {items}'

DQ=ArrayDeque()

DQ.enqueue_front(1)
DQ.enqueue_front(2)
DQ.enqueue_front(3)
DQ.enqueue_front(4)
DQ.enqueue_front(5)
DQ.enqueue_front(6)
DQ.enqueue_front(7)
DQ.enqueue_front(8)
DQ.enqueue_front(9)
DQ.enqueue_front(10)

print(DQ)

print('\nSize of the Deque:')
print(len(DQ))

print('\nitem at the back of the deque:')
print(DQ.last())

DQ.dequeue_front()
DQ.dequeue_back()

print ('\n\nAfter removing the first and last item:')
print(DQ)

print('\nSize of the Deque:')
print(len(DQ))




Deque: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

Size of the Deque:
10

item at the back of the deque:
1


After removing the first and last item:
Deque: [9, 8, 7, 6, 5, 4, 3, 2]

Size of the Deque:
8
